### ISSUE TITLE
Frontend Technology Research

### ISSUE THREAD

**Issue by denizgungor** [swe-ms-boun/2018fall-swe574-g2#10]
To be used technology for Front-end of the project will be investigated.

**Comment by yasserkabbout** [comment]
@enderalansoy Could you please suggest the best front-end framework to be used for this project? Do you recommend Angular, React or Vue?

**Comment by mehmetkayaalp** [comment]
I do not have much experience about them but, Vue or React is okay for me because as far as I know these two are very easy to adapt. @enderalansoy has more info about the front end so I think we can use Vue for the project.

**Comment by yasserkabbout** [comment]
@enderalansoy can you please post the pros/cons list? We can refer to it in order to give our decision.

**Comment by yasserkabbout** [comment]
After our meeting on the 20th of October, we decided to use "VUE.js" on the front-end side.
