### ISSUE TITLE
User Interface Prototyping

### ISSUE THREAD

**Issue by enderalansoy** [swe-ms-boun/2018fall-swe574-g2#18]
Creating sketches of screens. Suggestion to settle on the concepts on CW42 before or after the class via online meeting.

**Comment by yasserkabbout** [comment]
@enderalansoy I will post some reference websites in here. We should get the UI mockup done by the end of this week.

**Comment by yasserkabbout** [comment]
This task is in progress and will be done by the 22nd of October, 2018.

**Comment by enderalansoy** [comment]
Hi guys, can you please review the prototyping and comment on them so that I can revise according to your feedback? https://balsamiq.cloud/sc31zjf/pscjmcy

**Comment by yasserkabbout** [comment]
@enderalansoy The design is pretty good.. Could you just add a mockup for image annotation?
