### ISSUE TITLE
Github Rules will be described

### ISSUE THREAD

**Issue by mehmetkayaalp** [swe-ms-boun/2018fall-swe574-g2#30]

**Comment by mehmetkayaalp** [comment]
Umut added some rules. Here are the lists: 
1) Pull request's origin branch always will be to develop branch.
2) No one will commit directly to master branch or develop branch. 
3) At least 2 reviewers should approve the PR to merge it into develop branch. 
4) No one will not directly send a commit to develop branch. 
5) When a commit is about feature, the name of the branch should start with feature/ whereas when a commit is about solving a bug, the name of the branch should start with bug/.

**Comment by yasserkabbout** [comment]
@umutseven92 @mehmetkayaalp noted.
