### ISSUE TITLE
Initialization of Django Project 

### ISSUE THREAD

**Issue by mehmetkayaalp** [swe-ms-boun/2018fall-swe574-g2#45]
Django project should be created and settings of it should be adjusted.

**Comment by umutseven92** [comment]
Done.

**Comment by denizgungor** [comment]
2.7 python-django project's code needs to be merged with this django project.

**Comment by umutseven92** [comment]
No, it does not. You cannot merge a Python 2.7 project with a Python 3.x project. We continue from the Python 3.x one.
