### ISSUE TITLE
Adding Meeting notes of 06/10/2018 Meeting

### ISSUE THREAD

**Issue by yasserkabbout** [swe-ms-boun/2018fall-swe574-g2#5]

**Comment by yasserkabbout** [comment]
The notes should be added in https://github.com/swe-ms-boun/2018fall-swe574-g2/wiki/A.-Meetings-Schedule-&-Notes

**Comment by mehmetkayaalp** [comment]
@denizgungor added meeting notes for the first week so I am closing the PR.
