### ISSUE TITLE
Documenting Memories for Elicitation

### ISSUE THREAD

**Issue by yasserkabbout** [swe-ms-boun/2018fall-swe574-g2#6]
Memories should be documented in https://github.com/swe-ms-boun/2018fall-swe574-g2/wiki/3.-Memories-Collected

**Comment by yasserkabbout** [comment]
4 Memories have been submitted. @enderalansoy could you please add yours so we can move this task to DONE?

**Comment by mehmetkayaalp** [comment]
Alan added his history so I closed it.
