### ISSUE TITLE
API için gerekli Mongo'nun deployment'ı yapılmalı. 

### ISSUE THREAD

**Issue by mehmetkayaalp** [swe-ms-boun/2018fall-swe574-g2#64]

**Comment by enderalansoy** [comment]
A temporary deployment has been done on: mongodb://<dbuser>:<dbpassword>@ds127624.mlab.com:27624/thymesis

app.py has to be updated to reflect this

**Comment by mehmetkayaalp** [comment]
API has been deployed on Heroku.
